# This file was generated by GoReleaser. DO NOT EDIT.
cask "docker-sops" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "471bcd9cc651c56bdc14e15ae8f9e5e26ecf1faea78a4395d06a2341144264bb"
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_darwin_arm64"
      binary "docker-sops_0.2.0_darwin_arm64", target: "docker-sops"
    end
    on_intel do
      sha256 "e2663714bc49948f6dcb3e5fc5808fb670bb988c402519ed4d7069bce90a5fc2"
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_darwin_amd64"
      binary "docker-sops_0.2.0_darwin_amd64", target: "docker-sops"
    end
  end
  on_linux do
    on_arm do
      sha256 "92fe8759831878101f15af3dd4110cc30c750b5816aa7a894d57e97fc139cbb9"
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_linux_arm64"
      binary "docker-sops_0.2.0_linux_arm64", target: "docker-sops"
    end
    on_intel do
      sha256 "67873d26235c095e98dcbabef3de49a83e2edc5686d1e0ff2a0c5c899af5f367"
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_linux_amd64"
      binary "docker-sops_0.2.0_linux_amd64", target: "docker-sops"
    end
  end

  name "docker-sops"
  desc "Docker CLI plugin that lets docker commands consume sops-encrypted files without leaving plaintext behind"
  homepage "https://github.com/mohsen0/docker-sops"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    # The binary stanza installs the plugin as #{HOMEBREW_PREFIX}/bin/docker-sops;
    # Docker only discovers plugins in its cli-plugins directory, so link it there.
    plugins = "#{Dir.home}/.docker/cli-plugins"
    system_command "/bin/mkdir", args: ["-p", plugins]
    system_command "/bin/ln", args: ["-sfn", "#{HOMEBREW_PREFIX}/bin/docker-sops", "#{plugins}/docker-sops"]
  end

  # No zap stanza required

  caveats <<~EOS
    Installed as a Docker CLI plugin and linked into ~/.docker/cli-plugins.
    Run `docker sops --help` to get started.
  EOS
end
