# This file was generated by GoReleaser. DO NOT EDIT.
cask "docker-sops" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "795d8ba2623aac03001099b00fd658045092f17f3b6e7ce0d4f7f6b7ac503f62"
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_darwin_arm64"
      binary "docker-sops_0.2.1_darwin_arm64", target: "docker-sops"
    end
    on_intel do
      sha256 "1668a43e08b8d6d51a9a558ea313774b050ae24bd4bdd18bfc47b9dac0c8a4b8"
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_darwin_amd64"
      binary "docker-sops_0.2.1_darwin_amd64", target: "docker-sops"
    end
  end
  on_linux do
    on_arm do
      sha256 "c1dafdb04a9f1c4d143915d91c3d4687d737caef6e0be8d6a715ba2b9c39fe6c"
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_linux_arm64"
      binary "docker-sops_0.2.1_linux_arm64", target: "docker-sops"
    end
    on_intel do
      sha256 "89c854b84b5a886303d26ce28ed5b5cfb929f604f3da7e82a965207f8a6215de"
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_linux_amd64"
      binary "docker-sops_0.2.1_linux_amd64", target: "docker-sops"
    end
  end

  name "docker-sops"
  desc "Docker CLI plugin that lets docker commands consume sops-encrypted files without leaving plaintext behind"
  homepage "https://github.com/mohsen0/docker-sops"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    # The binary stanza installs the plugin as #{HOMEBREW_PREFIX}/bin/docker-sops;
    # Docker only discovers plugins in its cli-plugins directory, so link it there.
    plugins = "#{Dir.home}/.docker/cli-plugins"
    system_command "/bin/mkdir", args: ["-p", plugins]
    system_command "/bin/ln", args: ["-sfn", "#{HOMEBREW_PREFIX}/bin/docker-sops", "#{plugins}/docker-sops"]
  end

  # No zap stanza required

  caveats <<~EOS
    Installed as a Docker CLI plugin and linked into ~/.docker/cli-plugins.
    Run `docker sops --help` to get started.
  EOS
end
