# This file was generated by GoReleaser. DO NOT EDIT.
cask "docker-sops" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "b811431d6ec3f163fc0c83c33b4368b0157c6390e1462e995205ece6223c132a"
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_darwin_arm64"
      binary "docker-sops_0.2.0_darwin_arm64", target: "docker-sops"
    end
    on_intel do
      sha256 "fe2f1641f0f878eef0c93fe33c16d9276302dbbf6927d5ae31a97d207d6ff934"
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_darwin_amd64"
      binary "docker-sops_0.2.0_darwin_amd64", target: "docker-sops"
    end
  end
  on_linux do
    on_arm do
      sha256 "ff6dfd1d7adf51d928dfcefec89bbf255ea09689f335bc004060916ac1821d6a"
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_linux_arm64"
      binary "docker-sops_0.2.0_linux_arm64", target: "docker-sops"
    end
    on_intel do
      sha256 "a29ce17fc418d4f14ca3a2cfffff066cf1e23983e392072489705015fa57305f"
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_linux_amd64"
      binary "docker-sops_0.2.0_linux_amd64", target: "docker-sops"
    end
  end

  name "docker-sops"
  desc "Docker CLI plugin that lets docker commands consume sops-encrypted files without leaving plaintext behind"
  homepage "https://github.com/mohsen0/docker-sops"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    # The binary stanza installs the plugin as #{HOMEBREW_PREFIX}/bin/docker-sops;
    # Docker only discovers plugins in its cli-plugins directory, so link it there.
    plugins = "#{Dir.home}/.docker/cli-plugins"
    system_command "/bin/mkdir", args: ["-p", plugins]
    system_command "/bin/ln", args: ["-sfn", "#{HOMEBREW_PREFIX}/bin/docker-sops", "#{plugins}/docker-sops"]
  end

  # No zap stanza required

  caveats <<~EOS
    Installed as a Docker CLI plugin and linked into ~/.docker/cli-plugins.
    Run `docker sops --help` to get started.
  EOS
end
