# Generated by scripts/update-formula.sh on release. Do not edit by hand.
class DockerSops < Formula
  desc "Docker CLI plugin that decrypts sops-encrypted files on the fly"
  homepage "https://github.com/mohsen0/docker-sops"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_darwin_arm64"
      sha256 "5568d14ccbab8e75bad8490ccdbbf7124c3c757f196edf1f05157a04e17c9275"
    end
    on_intel do
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_darwin_amd64"
      sha256 "d85f4b9431ea5d6a72fa115226476c1eea91dd8da9badeb169ef85551db2370a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_linux_arm64"
      sha256 "161d864aee9801c4ad6b06fd414d5f08b3226101c796527d148db38b8427ab0e"
    end
    on_intel do
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_linux_amd64"
      sha256 "288f662a2aa0944406c708c2a68b786c95470829c452907d05f86d32cb4f6671"
    end
  end

  def install
    bin.install Dir["docker-sops_*"].first => "docker-sops"
  end

  def caveats
    <<~EOS
      Docker only discovers plugins in its cli-plugins directory. Link it once:

        mkdir -p ~/.docker/cli-plugins
        ln -sfn #{opt_bin}/docker-sops ~/.docker/cli-plugins/docker-sops

      Then run: docker sops --help
    EOS
  end

  test do
    assert_match "docker-sops version #{version}", shell_output("#{bin}/docker-sops sops version")
  end
end
