# Generated by scripts/update-formula.sh on release. Do not edit by hand.
class DockerSops < Formula
  desc "Docker CLI plugin that decrypts sops-encrypted files on the fly"
  homepage "https://github.com/mohsen0/docker-sops"
  version "0.2.2"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_darwin_arm64"
      sha256 "73a3db8c28b1f296b002549cb50ffd43e9276d201d86ab494521815c86ae893e"
    end
    on_intel do
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_darwin_amd64"
      sha256 "e31281bce540ff1979a8b30604809f6edc586a112e758623a27e2b667d89c89c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_linux_arm64"
      sha256 "89f4331241dd9a555dd4cd9d837621fec2e1dcb563daca725c1b713e6c43f66c"
    end
    on_intel do
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_linux_amd64"
      sha256 "cab43f83ce53e9c8fb75b688f0648e193a6739362221cbb17978b6b6da20b349"
    end
  end

  def install
    bin.install Dir["docker-sops_*"].first => "docker-sops"
  end

  def caveats
    <<~EOS
      Docker only discovers plugins in its cli-plugins directory. Link it once:

        mkdir -p ~/.docker/cli-plugins
        ln -sfn #{opt_bin}/docker-sops ~/.docker/cli-plugins/docker-sops

      Then run: docker sops --help
    EOS
  end

  test do
    assert_match "docker-sops version #{version}", shell_output("#{bin}/docker-sops sops version")
  end
end
