# Generated by scripts/update-formula.sh on release. Do not edit by hand.
class DockerSops < Formula
  desc "Docker CLI plugin that decrypts sops-encrypted files on the fly"
  homepage "https://github.com/mohsen0/docker-sops"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_darwin_arm64"
      sha256 "795d8ba2623aac03001099b00fd658045092f17f3b6e7ce0d4f7f6b7ac503f62"
    end
    on_intel do
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_darwin_amd64"
      sha256 "1668a43e08b8d6d51a9a558ea313774b050ae24bd4bdd18bfc47b9dac0c8a4b8"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_linux_arm64"
      sha256 "c1dafdb04a9f1c4d143915d91c3d4687d737caef6e0be8d6a715ba2b9c39fe6c"
    end
    on_intel do
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_linux_amd64"
      sha256 "89c854b84b5a886303d26ce28ed5b5cfb929f604f3da7e82a965207f8a6215de"
    end
  end

  def install
    bin.install Dir["docker-sops_*"].first => "docker-sops"
  end

  def caveats
    <<~EOS
      Docker only discovers plugins in its cli-plugins directory. Link it once:

        mkdir -p ~/.docker/cli-plugins
        ln -sfn #{opt_bin}/docker-sops ~/.docker/cli-plugins/docker-sops

      Then run: docker sops --help
    EOS
  end

  test do
    assert_match "docker-sops version #{version}", shell_output("#{bin}/docker-sops sops version")
  end
end
