Third-party licenses
=====================

docker-sops (https://github.com/mohsen0/docker-sops) includes the
following third-party Go modules. This report is generated by
`go-licenses report` (see `make licenses`); do not edit by hand.

{{ range . }}
{{ .Name }} ({{ .Version }})
  License: {{ .LicenseName }}
  URL:     {{ .LicenseURL }}
{{ end }}
