#!/bin/sh
# Rewrite Formula/docker-sops.rb for a release.
# Usage: scripts/update-formula.sh <version-without-v> <path-to-checksums.txt>
set -eu

VERSION=$1
CHECKSUMS=$2
FORMULA=$(dirname "$0")/../Formula/docker-sops.rb

sha() {
	grep " docker-sops_${VERSION}_$1\$" "$CHECKSUMS" | awk '{print $1}'
}

DARWIN_ARM64=$(sha darwin_arm64)
DARWIN_AMD64=$(sha darwin_amd64)
LINUX_ARM64=$(sha linux_arm64)
LINUX_AMD64=$(sha linux_amd64)
for v in "$DARWIN_ARM64" "$DARWIN_AMD64" "$LINUX_ARM64" "$LINUX_AMD64"; do
	[ -n "$v" ] || { echo "missing checksum for version $VERSION in $CHECKSUMS" >&2; exit 1; }
done

cat > "$FORMULA" <<RUBY
# Generated by scripts/update-formula.sh on release. Do not edit by hand.
class DockerSops < Formula
  desc "Docker CLI plugin that decrypts sops-encrypted files on the fly"
  homepage "https://github.com/mohsen0/docker-sops"
  version "${VERSION}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_darwin_arm64"
      sha256 "${DARWIN_ARM64}"
    end
    on_intel do
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_darwin_amd64"
      sha256 "${DARWIN_AMD64}"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_linux_arm64"
      sha256 "${LINUX_ARM64}"
    end
    on_intel do
      url "https://github.com/mohsen0/docker-sops/releases/download/v#{version}/docker-sops_#{version}_linux_amd64"
      sha256 "${LINUX_AMD64}"
    end
  end

  def install
    bin.install Dir["docker-sops_*"].first => "docker-sops"
  end

  def caveats
    <<~EOS
      Docker only discovers plugins in its cli-plugins directory. Link it once:

        mkdir -p ~/.docker/cli-plugins
        ln -sfn #{opt_bin}/docker-sops ~/.docker/cli-plugins/docker-sops

      Then run: docker sops --help
    EOS
  end

  test do
    assert_match "docker-sops version #{version}", shell_output("#{bin}/docker-sops sops version")
  end
end
RUBY
echo "updated $FORMULA for ${VERSION}"
